import string
print(string.ascii_letters)
print('-'*30)
print(string.digits)
print('-'*30)
print(string.ascii_lowercase)
print('-'*30)
print(string.ascii_uppercase)
print('-'*30)
print(string.hexdigits)
print('-'*30)
print(string.octdigits)
print('-'*30)
print(string.punctuation)
